{
  "snapshot_0": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "23",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 5",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_1": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "23",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 5",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_2": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "23",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 5",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_3": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "23",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 5",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_4": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "23",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 5",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_5": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "23",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 5",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_6": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "23",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 5",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  }
}