[
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "16"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursion",
        "lineNumber": 16
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "16": {
          "arguments": {},
          "locals": {
            "depth": {
              "type": "int",
              "value": "5"
            },
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception depth 5'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursion",
                "lineNumber": 16
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 23
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "21"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursion",
        "lineNumber": 16
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "21": {
          "arguments": {
            "originalDepth": {
              "type": "int",
              "value": "5"
            },
            "currentDepth": {
              "type": "int",
              "value": "5"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception depth 5'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursion",
                "lineNumber": 16
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 23
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "21"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursion",
        "lineNumber": 16
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "21": {
          "arguments": {
            "originalDepth": {
              "type": "int",
              "value": "5"
            },
            "currentDepth": {
              "type": "int",
              "value": "4"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception depth 5'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursion",
                "lineNumber": 16
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 23
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "21"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursion",
        "lineNumber": 16
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "21": {
          "arguments": {
            "originalDepth": {
              "type": "int",
              "value": "5"
            },
            "currentDepth": {
              "type": "int",
              "value": "3"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception depth 5'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursion",
                "lineNumber": 16
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 23
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "21"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursion",
        "lineNumber": 16
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "21": {
          "arguments": {
            "originalDepth": {
              "type": "int",
              "value": "5"
            },
            "currentDepth": {
              "type": "int",
              "value": "2"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception depth 5'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursion",
                "lineNumber": 16
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 23
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "21"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursion",
        "lineNumber": 16
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "21": {
          "arguments": {
            "originalDepth": {
              "type": "int",
              "value": "5"
            },
            "currentDepth": {
              "type": "int",
              "value": "1"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception depth 5'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursion",
                "lineNumber": 16
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 23
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "23"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 23
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursionHelper",
        "lineNumber": 21
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exceptionReplayRecursion",
        "lineNumber": 16
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "23": {
          "arguments": {
            "originalDepth": {
              "type": "int",
              "value": "5"
            },
            "currentDepth": {
              "type": "int",
              "value": "0"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception depth 5'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursion",
                "lineNumber": 16
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 21
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exceptionReplayRecursionHelper",
                "lineNumber": 23
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  }
]