{
  "snapshot_0": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_1": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_2": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_3": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_4": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_5": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_6": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_7": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_8": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_9": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_10": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.2.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.2.function": "exceptionReplayRecursion",
      "_dd.debug.error.2.line": "16",
      "_dd.debug.error.2.snapshot_id": "<scrubbed>",
      "_dd.debug.error.3.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.3.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.3.line": "21",
      "_dd.debug.error.3.snapshot_id": "<scrubbed>",
      "_dd.debug.error.4.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.4.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.4.line": "21",
      "_dd.debug.error.4.snapshot_id": "<scrubbed>",
      "_dd.debug.error.5.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.5.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.5.line": "21",
      "_dd.debug.error.5.snapshot_id": "<scrubbed>",
      "_dd.debug.error.6.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.6.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.6.line": "21",
      "_dd.debug.error.6.snapshot_id": "<scrubbed>",
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.7.line": "21",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.8.line": "21",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  }
}