{
  "snapshot_0": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_1": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_2": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_3": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_4": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_5": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_6": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_7": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_8": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_9": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_10": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_11": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_12": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_13": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_14": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_15": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_16": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_17": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_18": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_19": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_20": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_21": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.10.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.10.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.10.line": "21",
      "_dd.debug.error.10.snapshot_id": "<scrubbed>",
      "_dd.debug.error.11.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.11.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.11.line": "21",
      "_dd.debug.error.11.snapshot_id": "<scrubbed>",
      "_dd.debug.error.12.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.12.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.12.line": "21",
      "_dd.debug.error.12.snapshot_id": "<scrubbed>",
      "_dd.debug.error.13.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.13.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.13.line": "21",
      "_dd.debug.error.13.snapshot_id": "<scrubbed>",
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "21",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.24.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.24.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.24.line": "21",
      "_dd.debug.error.24.snapshot_id": "<scrubbed>",
      "_dd.debug.error.25.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.25.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.25.line": "21",
      "_dd.debug.error.25.snapshot_id": "<scrubbed>",
      "_dd.debug.error.26.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.26.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.26.line": "21",
      "_dd.debug.error.26.snapshot_id": "<scrubbed>",
      "_dd.debug.error.27.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.27.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.27.line": "21",
      "_dd.debug.error.27.snapshot_id": "<scrubbed>",
      "_dd.debug.error.28.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.28.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.28.line": "21",
      "_dd.debug.error.28.snapshot_id": "<scrubbed>",
      "_dd.debug.error.29.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.29.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.29.line": "23",
      "_dd.debug.error.29.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "exceptionReplayRecursion",
      "_dd.debug.error.8.line": "16",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.9.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.9.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.9.line": "21",
      "_dd.debug.error.9.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.handle_user_exception",
    "parentID": "<scrubbed>",
    "resource": "flask.handle_user_exception",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  }
}