{
  "snapshot_0": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.appsec.event_rules.version": "<scrubbed>",
      "_dd.debug.error.0.frame_data.class_name": "DebuggerController",
      "_dd.debug.error.0.frame_data.function": "ExceptionReplayInner",
      "_dd.debug.error.0.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "_dd.di._eh": "-1498658543",
      "_dd.di._er": "Eligible",
      "_dd.iast.enabled": "1",
      "_dd.runtime_family": "dotnet",
      "aspnet_core.endpoint": "weblog.DebuggerController.ExceptionReplayInner (app)",
      "aspnet_core.route": "debugger/exceptionreplay/inner",
      "component": "aspnet_core",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.msg": "Outer exception",
      "error.stack": "System.Exception: Outer exception\n ---> System.Exception: Inner exception\n   at weblog.DebuggerController.ExceptionReplayInner()<scrubbed>",
      "error.type": "System.Exception",
      "http.client_ip": "<scrubbed>",
      "http.method": "GET",
      "http.request.headers.host": "localhost:7777",
      "http.request.headers.user-agent": "<scrubbed>",
      "http.route": "debugger/exceptionreplay/inner",
      "http.status_code": "500",
      "http.url": "http://localhost:7777/debugger/exceptionreplay/inner",
      "http.useragent": "<scrubbed>",
      "key1": "val1",
      "key2": "val2",
      "language": "dotnet",
      "network.client.ip": "<scrubbed>",
      "runtime-id": "<scrubbed>",
      "span.kind": "server",
      "version": "<scrubbed>"
    },
    "metrics": "<scrubbed>",
    "name": "aspnet_core.request",
    "resource": "GET /debugger/exceptionreplay/inner",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>",
    "type": "web"
  }
}