{
  "snapshot_0": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exception_replay_async",
      "_dd.debug.error.7.line": "69",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "_async_throw",
      "_dd.debug.error.8.line": "64",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "async exception",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/patch.py\", lin<scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.dispatch_request",
    "parentID": "<scrubbed>",
    "resource": "flask.dispatch_request",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_1": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.7.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.7.function": "exception_replay_async",
      "_dd.debug.error.7.line": "69",
      "_dd.debug.error.7.snapshot_id": "<scrubbed>",
      "_dd.debug.error.8.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.8.function": "_async_throw",
      "_dd.debug.error.8.line": "64",
      "_dd.debug.error.8.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "async exception",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/patch.py\", lin<scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "flask.dispatch_request",
    "parentID": "<scrubbed>",
    "resource": "flask.dispatch_request",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  }
}