{
  "snapshot_0": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_1": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_2": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_3": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_4": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_5": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_6": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_7": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_8": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  },
  "snapshot_9": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.debug.error.14.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.14.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.14.line": "21",
      "_dd.debug.error.14.snapshot_id": "<scrubbed>",
      "_dd.debug.error.15.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.15.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.15.line": "21",
      "_dd.debug.error.15.snapshot_id": "<scrubbed>",
      "_dd.debug.error.16.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.16.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.16.line": "21",
      "_dd.debug.error.16.snapshot_id": "<scrubbed>",
      "_dd.debug.error.17.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.17.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.17.line": "21",
      "_dd.debug.error.17.snapshot_id": "<scrubbed>",
      "_dd.debug.error.18.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.18.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.18.line": "21",
      "_dd.debug.error.18.snapshot_id": "<scrubbed>",
      "_dd.debug.error.19.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.19.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.19.line": "21",
      "_dd.debug.error.19.snapshot_id": "<scrubbed>",
      "_dd.debug.error.20.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.20.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.20.line": "21",
      "_dd.debug.error.20.snapshot_id": "<scrubbed>",
      "_dd.debug.error.21.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.21.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.21.line": "21",
      "_dd.debug.error.21.snapshot_id": "<scrubbed>",
      "_dd.debug.error.22.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.22.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.22.line": "21",
      "_dd.debug.error.22.snapshot_id": "<scrubbed>",
      "_dd.debug.error.23.file": "/app/exception_replay_controller.py",
      "_dd.debug.error.23.function": "exceptionReplayRecursionHelper",
      "_dd.debug.error.23.line": "23",
      "_dd.debug.error.23.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_capture_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "component": "flask",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "recursion exception depth 20",
      "error.stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/ddtrace/contrib/internal/flask/wrappers.py\", <scrubbed>",
      "error.type": "builtins.Exception",
      "key1": "val1",
      "key2": "val2",
      "version": "<scrubbed>"
    },
    "name": "exceptionreplay.exceptionReplayRecursion",
    "parentID": "<scrubbed>",
    "resource": "/exceptionreplay/recursion",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>"
  }
}